
import React from 'react';
import { ArrowRight } from 'lucide-react';
import { MessagingArchitecture } from '../../types/adsEngine';

interface StepMessagingProps {
    data: MessagingArchitecture;
    onNext: () => void;
}

export const StepMessaging: React.FC<StepMessagingProps> = ({ data, onNext }) => {
    return (
        <div className="space-y-8 animate-in fade-in zoom-in-95 duration-500">
            <div className="flex justify-between items-end">
                <div>
                    <h2 className="text-2xl font-bold text-white mb-2">Messaging Architecture</h2>
                    <p className="text-slate-400">Strategic positioning and psychological hooks generated by AI.</p>
                </div>
                <button onClick={onNext} className="bg-blue-600 hover:bg-blue-500 text-white px-6 py-2 rounded-lg transition-colors flex items-center gap-2 shadow-lg shadow-blue-900/20">
                    Generate Creatives <ArrowRight size={16} />
                </button>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                <div className="space-y-6">
                    <div className="bg-gradient-to-br from-indigo-900/40 to-slate-900/50 p-6 rounded-2xl border border-indigo-500/30 relative overflow-hidden">
                        <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-500/10 rounded-full blur-3xl -mr-16 -mt-16 pointer-events-none"></div>
                        <h3 className="text-indigo-300 font-medium text-sm uppercase tracking-wider mb-2">Core Value Proposition</h3>
                        <p className="text-2xl font-light text-white leading-relaxed">"{data.coreValueProp}"</p>
                    </div>

                    <div className="bg-slate-900/50 p-6 rounded-2xl border border-slate-800">
                        <h3 className="text-slate-400 text-sm uppercase tracking-wider mb-3">Positioning Statement</h3>
                        <p className="text-lg text-slate-200">{data.positioningStatement}</p>
                    </div>
                </div>

                <div className="bg-slate-900/50 p-6 rounded-2xl border border-slate-800 flex flex-col h-full">
                    <h3 className="text-white font-semibold mb-4">High-Converting Hooks</h3>
                    <div className="space-y-3 flex-1">
                        {data.hooks?.map((hook, i) => (
                            <div key={i} className="flex gap-3 items-start p-3 hover:bg-slate-800/50 rounded-lg transition-colors cursor-default">
                                <div className="bg-blue-500/20 text-blue-400 w-6 h-6 rounded-full flex items-center justify-center text-xs flex-shrink-0 mt-0.5">
                                    {i + 1}
                                </div>
                                <p className="text-slate-300">{hook}</p>
                            </div>
                        )) || <p className="text-slate-500 text-sm">No hooks generated.</p>}
                    </div>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {data.messagingAngles?.map((angle, i) => (
                    <div key={i} className="bg-slate-950 border border-slate-800 p-4 rounded-xl">
                        <h4 className="font-semibold text-blue-300 mb-2">{angle.angle}</h4>
                        <p className="text-sm text-slate-500">{angle.description}</p>
                    </div>
                )) || <p className="text-slate-500 text-sm col-span-3">No angles generated.</p>}
            </div>
        </div>
    );
};
